# 1.Import the Necessory Libraries

In [1]:
import pandas as pd

# 2.Import The Dataset

In [2]:
movies_data=pd.read_csv("Movie.csv")
movies_data

      userId             movie  rating
0          3  Toy Story (1995)     4.0
1          6  Toy Story (1995)     5.0
2          8  Toy Story (1995)     4.0
3         10  Toy Story (1995)     4.0
4         11  Toy Story (1995)     4.5
...      ...               ...     ...
8987    7087  GoldenEye (1995)     3.0
8988    7088  GoldenEye (1995)     1.0
8989    7105  GoldenEye (1995)     2.0
8990    7113  GoldenEye (1995)     3.0
8991    7117  GoldenEye (1995)     3.0

[8992 rows x 3 columns]

# 3.Data Understanding

In [3]:
movies_data.shape

(8992, 3)

In [12]:
movies_data["userId"].unique()

array([   3,    6,    8, ..., 7080, 7087, 7105], shape=(4081,))

In [13]:
movies_data["userId"].nunique()

4081

In [14]:
movies_data["movie"].nunique()

10

In [16]:
movies_data["movie"].unique()

array(['Toy Story (1995)', 'Jumanji (1995)', 'Grumpier Old Men (1995)',
       'Waiting to Exhale (1995)', 'Father of the Bride Part II (1995)',
       'Heat (1995)', 'Sabrina (1995)', 'Tom and Huck (1995)',
       'Sudden Death (1995)', 'GoldenEye (1995)'], dtype=object)

In [5]:
movies_data.isna().sum()

userId    0
movie     0
rating    0
dtype: int64

In [6]:
movies_data.describe()

            userId       rating
count  8992.000000  8992.000000
mean   3521.880116     3.557162
std    2012.497384     0.967071
min       1.000000     0.500000
25%    1779.000000     3.000000
50%    3530.000000     3.500000
75%    5213.250000     4.000000
max    7120.000000     5.000000

In [7]:
movies_data.dtypes

userId      int64
movie      object
rating    float64
dtype: object

# 4.Data Preparation| model building

In [18]:
piv_table=pd.pivot_table(data=movies_data,values="rating",index="movie",columns="userId").fillna(0)
piv_table.columns=movies_data["userId"].unique()
piv_table

,3,6,8,10,11,12,13,14,16,19,...,6975,6979,6993,7030,7031,7044,7070,7080,7087,7105
movie,,,,,,,,,,,,,,,,,,,,,
Father of the Bride Part II (1995),0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,4.0,3.5,0.0,0.0,0.0
GoldenEye (1995),0.0,0.0,0.0,4.0,0.0,0.0,0.0,4.0,0.0,2.5,...,2.0,0.0,0.0,0.0,3.0,0.0,0.0,3.0,0.0,0.0
Grumpier Old Men (1995),0.0,4.0,0.0,0.0,0.0,3.0,3.0,5.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,4.0,0.0,0.0
Heat (1995),0.0,0.0,0.0,3.0,0.0,0.0,0.0,3.0,0.0,0.0,...,0.0,0.0,0.0,0.0,3.0,0.0,0.0,5.0,0.0,0.0
Jumanji (1995),3.5,0.0,0.0,0.0,3.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,2.0,4.0,0.0,0.0,0.0,0.0,0.0,4.0
Sabrina (1995),0.0,0.0,0.0,0.0,0.0,5.0,3.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,3.0,0.0,4.0
Sudden Death (1995),0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0
Tom and Huck (1995),0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
Toy Story (1995),0.0,0.0,4.0,0.0,0.0,5.0,0.0,4.0,4.0,4.5,...,0.0,4.0,0.0,4.0,0.0,0.0,4.0,4.0,5.0,4.5
Waiting to Exhale (1995),0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [20]:
piv_table.corr().round(2)

,3,6,8,10,11,12,13,14,16,19,...,6975,6979,6993,7030,7031,7044,7070,7080,7087,7105
3,1.00,-0.11,-0.11,-0.16,1.00,-0.21,-0.17,-0.27,-0.11,-0.16,...,-0.11,-0.11,1.00,0.67,-0.17,-0.11,-0.17,-0.35,-0.11,0.48
6,-0.11,1.00,-0.11,-0.16,-0.11,0.28,0.67,0.56,-0.11,-0.16,...,-0.11,-0.11,-0.11,-0.17,-0.17,-0.11,-0.17,0.35,-0.11,-0.22
8,-0.11,-0.11,1.00,-0.16,-0.11,0.60,-0.17,0.40,1.00,0.86,...,-0.11,1.00,-0.11,0.67,-0.17,-0.11,0.72,0.35,1.00,0.57
10,-0.16,-0.16,-0.16,1.00,-0.16,-0.31,-0.25,0.48,-0.16,0.24,...,0.78,-0.16,-0.16,-0.25,0.99,-0.16,-0.25,0.48,-0.16,-0.32
11,1.00,-0.11,-0.11,-0.16,1.00,-0.21,-0.17,-0.27,-0.11,-0.16,...,-0.11,-0.11,1.00,0.67,-0.17,-0.11,-0.17,-0.35,-0.11,0.48
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7044,-0.11,-0.11,-0.11,-0.16,-0.11,-0.21,-0.17,-0.27,-0.11,-0.16,...,-0.11,-0.11,-0.11,-0.17,-0.17,1.00,0.61,-0.35,-0.11,-0.22
7070,-0.17,-0.17,0.72,-0.25,-0.17,0.33,-0.25,0.13,0.72,0.58,...,-0.17,0.72,-0.17,0.42,-0.25,0.61,1.00,0.04,0.72,0.30
7080,-0.35,0.35,0.35,0.48,-0.35,0.54,0.40,0.81,0.35,0.41,...,0.18,0.35,-0.35,0.00,0.53,-0.35,0.04,1.00,0.35,0.14
7087,-0.11,-0.11,1.00,-0.16,-0.11,0.60,-0.17,0.40,1.00,0.86,...,-0.11,1.00,-0.11,0.67,-0.17,-0.11,0.72,0.35,1.00,0.57
7105,0.48,-0.22,0.57,-0.32,0.48,0.67,0.20,-0.05,0.57,0.41,...,-0.22,0.57,0.48,0.78,-0.33,-0.22,0.30,0.14,0.57,1.00

In [26]:
movies_data[(movies_data["userId"]==3)|(movies_data["userId"]==11)]

      userId             movie  rating
0          3  Toy Story (1995)     4.0
4         11  Toy Story (1995)     4.5
7446      11  GoldenEye (1995)     2.5

# 2.Buildinf UBCH using euclideon  distance

In [27]:
from sklearn.metrics import pairwise_distances

In [29]:
euclidion_piv_table=pd.pivot_table(data=movies_data,values="rating",index="userId",columns="movie").fillna(0)
euclidion_piv_table.columns=movies_data["movie"].unique()
euclidion_piv_table.index=movies_data["userId"].unique()
euclidion_piv_table

,Toy Story (1995),Jumanji (1995),Grumpier Old Men (1995),Waiting to Exhale (1995),Father of the Bride Part II (1995),Heat (1995),Sabrina (1995),Tom and Huck (1995),Sudden Death (1995),GoldenEye (1995)
3,0.0,0.0,0.0,0.0,3.5,0.0,0.0,0.0,0.0,0.0
6,0.0,0.0,4.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
8,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,4.0,0.0
10,0.0,4.0,0.0,3.0,0.0,0.0,0.0,0.0,0.0,0.0
11,0.0,0.0,0.0,0.0,3.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...
7044,4.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
7070,3.5,0.0,0.0,0.0,0.0,0.0,0.0,0.0,4.0,0.0
7080,0.0,3.0,4.0,5.0,0.0,3.0,1.0,0.0,4.0,0.0
7087,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,5.0,0.0
7105,0.0,0.0,0.0,0.0,4.0,4.0,0.0,0.0,4.5,0.0

In [33]:
eulidion_correlation=pd.DataFrame(pairwise_distances(X=euclidion_piv_table,metric='euclidean'))
eulidion_correlation.columns=movies_data["userId"].unique()
eulidion_correlation.index=movies_data["userId"].unique()
eulidion_correlation.round(2)

,3,6,8,10,11,12,13,14,16,19,...,6975,6979,6993,7030,7031,7044,7070,7080,7087,7105
3,0.00,5.32,5.32,6.10,0.50,8.44,5.50,8.85,5.32,6.22,...,4.03,5.32,1.50,4.03,5.50,5.32,6.36,9.39,6.10,6.04
6,5.32,0.00,5.66,6.40,5.00,7.14,3.16,6.48,5.66,6.52,...,4.47,5.66,4.47,6.93,5.83,5.66,6.65,7.75,6.40,8.26
8,5.32,5.66,0.00,6.40,5.00,5.92,5.83,7.07,0.00,2.55,...,4.47,0.00,4.47,4.00,5.83,5.66,3.50,7.75,1.00,5.68
10,6.10,6.40,6.40,0.00,5.83,9.17,6.56,6.40,6.40,5.61,...,3.61,6.40,5.39,7.55,1.00,6.40,7.30,6.86,7.07,8.79
11,0.50,5.00,5.00,5.83,0.00,8.25,5.20,8.66,5.00,5.96,...,3.61,5.00,1.00,4.12,5.20,5.00,6.10,9.22,5.83,6.10
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7044,5.32,5.66,5.66,6.40,5.00,8.66,5.83,9.06,5.66,6.52,...,4.47,5.66,4.47,6.93,5.83,0.00,4.03,9.59,6.40,8.26
7070,6.36,6.65,3.50,7.30,6.10,6.87,6.80,7.89,3.50,4.33,...,5.68,3.50,5.68,5.32,6.80,4.03,0.00,8.50,3.64,6.67
7080,9.39,7.75,7.75,6.86,9.22,6.40,7.21,4.00,7.75,7.18,...,8.25,7.75,8.94,8.72,6.78,9.59,8.50,0.00,7.81,8.26
7087,6.10,6.40,1.00,7.07,5.83,5.83,6.56,7.14,1.00,2.55,...,5.39,1.00,5.39,4.12,6.56,6.40,3.64,7.81,0.00,5.68
7105,6.04,8.26,5.68,8.79,6.10,5.12,6.80,9.07,5.68,6.18,...,7.50,5.68,6.34,4.03,8.38,8.26,6.67,8.26,5.68,0.00

# 3.Buildinf UBCH using cosine similarity

In [35]:
cosine_correlation=pd.DataFrame(1-pairwise_distances(X=euclidion_piv_table,metric='cosine'))
cosine_correlation.columns=movies_data["userId"].unique()
cosine_correlation.index=movies_data["userId"].unique()
cosine_correlation.round(2)

,3,6,8,10,11,12,13,14,16,19,...,6975,6979,6993,7030,7031,7044,7070,7080,7087,7105
3,1.00,0.00,0.00,0.00,1.00,0.00,0.00,0.00,0.00,0.00,...,0.00,0.00,1.00,0.71,0.00,0.00,0.00,0.00,0.00,0.55
6,0.00,1.00,0.00,0.00,0.00,0.39,0.71,0.62,0.00,0.00,...,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.46,0.00,0.00
8,0.00,0.00,1.00,0.00,0.00,0.65,0.00,0.49,1.00,0.87,...,0.00,1.00,0.00,0.71,0.00,0.00,0.75,0.46,1.00,0.62
10,0.00,0.00,0.00,1.00,0.00,0.00,0.00,0.62,0.00,0.39,...,0.80,0.00,0.00,0.00,0.99,0.00,0.00,0.62,0.00,0.00
11,1.00,0.00,0.00,0.00,1.00,0.00,0.00,0.00,0.00,0.00,...,0.00,0.00,1.00,0.71,0.00,0.00,0.00,0.00,0.00,0.55
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7044,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,...,0.00,0.00,0.00,0.00,0.00,1.00,0.66,0.00,0.00,0.00
7070,0.00,0.00,0.75,0.00,0.00,0.49,0.00,0.37,0.75,0.66,...,0.00,0.75,0.00,0.53,0.00,0.66,1.00,0.35,0.75,0.47
7080,0.00,0.46,0.46,0.62,0.00,0.70,0.57,0.89,0.46,0.57,...,0.34,0.46,0.00,0.32,0.65,0.00,0.35,1.00,0.46,0.48
7087,0.00,0.00,1.00,0.00,0.00,0.65,0.00,0.49,1.00,0.87,...,0.00,1.00,0.00,0.71,0.00,0.00,0.75,0.46,1.00,0.62
7105,0.55,0.00,0.62,0.00,0.55,0.77,0.39,0.31,0.62,0.54,...,0.00,0.62,0.55,0.83,0.00,0.00,0.47,0.48,0.62,1.00

## Analyse for first 20 Observation

In [39]:
eulidion_correlation.iloc[:20,:20]

,3,6,8,10,11,12,13,14,16,19,22,23,24,31,34,39,47,53,54,58
3,0.000000,5.315073,5.315073,6.103278,0.500000,8.440972,5.500000,8.845903,5.315073,6.224950,7.697402,5.024938,6.689544,4.031129,5.500000,5.315073,10.161201,5.315073,6.800735,5.315073
6,5.315073,0.000000,5.656854,6.403124,5.000000,7.141428,3.162278,6.480741,5.656854,6.519202,6.244998,7.071068,6.964194,4.472136,5.830952,5.656854,8.660254,5.656854,7.071068,5.656854
8,5.315073,5.656854,0.000000,6.403124,5.000000,5.916080,5.830952,7.071068,0.000000,2.549510,5.567764,4.242641,3.535534,4.472136,3.162278,5.656854,8.185353,5.656854,5.099020,0.000000
10,6.103278,6.403124,6.403124,0.000000,5.830952,9.165151,6.557439,6.403124,6.403124,5.612486,7.348469,5.916080,7.582875,3.605551,5.000000,4.123106,9.273618,4.123106,5.385165,6.403124
11,0.500000,5.000000,5.000000,5.830952,0.000000,8.246211,5.196152,8.660254,5.000000,5.958188,7.483315,5.000000,6.442049,3.605551,5.196152,5.000000,10.000000,5.000000,6.557439,5.000000
12,8.440972,7.141428,5.916080,9.165151,8.246211,0.000000,5.385165,7.416198,5.916080,6.363961,4.242641,7.280110,3.391165,7.937254,6.855655,8.660254,5.099020,8.660254,7.937254,5.916080
13,5.500000,3.162278,5.830952,6.557439,5.196152,5.385165,0.000000,7.348469,5.830952,6.670832,5.385165,7.211103,5.431390,4.690416,6.000000,5.830952,7.416198,5.830952,7.211103,5.830952
14,8.845903,6.480741,7.071068,6.403124,8.660254,7.416198,7.348469,0.000000,7.071068,6.041523,5.744563,6.633250,7.905694,7.348469,6.480741,7.615773,6.855655,7.615773,6.782330,7.071068
16,5.315073,5.656854,0.000000,6.403124,5.000000,5.916080,5.830952,7.071068,0.000000,2.549510,5.567764,4.242641,3.535534,4.472136,3.162278,5.656854,8.185353,5.656854,5.099020,0.000000
19,6.224950,6.519202,2.549510,5.612486,5.958188,6.363961,6.670832,6.041523,2.549510,0.000000,6.123724,3.082207,4.301163,4.527693,4.183300,6.519202,8.514693,6.519202,5.787918,2.549510
22,7.697402,6.244998,5.567764,7.348469,7.483315,4.242641,5.385165,5.744563,5.567764,6.123724,0.000000,7.000000,4.743416,7.141428,4.795832,6.244998,3.741657,6.244998,5.196152,5.567764
23,5.024938,7.071068,4.242641,5.916080,5.000000,7.280110,7.211103,6.633250,4.242641,3.082207,7.000000,0.000000,5.522681,5.099020,5.291503,7.071068,9.219544,7.071068,6.633250,4.242641
24,6.689544,6.964194,3.535534,7.582875,6.442049,3.391165,5.431390,7.905694,3.535534,4.301163,4.743416,5.522681,0.000000,6.041523,4.847680,6.964194,6.595453,6.964194,6.284903,3.535534
31,4.031129,4.472136,4.472136,3.605551,3.605551,7.937254,4.690416,7.348469,4.472136,4.527693,7.141428,5.099020,6.041523,0.000000,4.690416,4.472136,9.746794,4.472136,6.164414,4.472136
34,5.500000,5.830952,3.162278,5.000000,5.196152,6.855655,6.000000,6.480741,3.162278,4.183300,4.795832,5.291503,4.847680,4.690416,0.000000,3.162278,7.000000,3.162278,2.000000,3.162278
39,5.315073,5.656854,5.656854,4.123106,5.000000,8.660254,5.830952,7.615773,5.656854,6.519202,6.244998,7.071068,6.964194,4.472136,3.162278,0.000000,8.185353,0.000000,3.162278,5.656854
47,10.161201,8.660254,8.185353,9.273618,10.000000,5.099020,7.416198,6.855655,8.185353,8.514693,3.741657,9.219544,6.595453,9.746794,7.000000,8.185353,0.000000,8.185353,6.708204,8.185353
53,5.315073,5.656854,5.656854,4.123106,5.000000,8.660254,5.830952,7.615773,5.656854,6.519202,6.244998,7.071068,6.964194,4.472136,3.162278,0.000000,8.185353,0.000000,3.162278,5.656854
54,6.800735,7.071068,5.099020,5.385165,6.557439,7.937254,7.211103,6.782330,5.099020,5.787918,5.196152,6.633250,6.284903,6.164414,2.000000,3.162278,6.708204,3.162278,0.000000,5.099020
58,5.315073,5.656854,0.000000,6.403124,5.000000,5.916080,5.830952,7.071068,0.000000,2.549510,5.567764,4.242641,3.535534,4.472136,3.162278,5.656854,8.185353,5.656854,5.099020,0.000000

In [42]:
movies_data[(movies_data["userId"]==12)|(movies_data["userId"]==23)]

      userId                               movie  rating
5         12                    Toy Story (1995)     4.0
11        23                    Toy Story (1995)     4.0
3728      12             Grumpier Old Men (1995)     3.0
4547      12  Father of the Bride Part II (1995)     2.0
5206      12                         Heat (1995)     3.0
6466      12                      Sabrina (1995)     3.0

# the end